dependencies {
    implementation project(':headlessmc-version')

    implementation project(':headlessmc-net')
    implementation project(':headlessmc-net:headlessmc-net-hash')
    implementation project(':headlessmc-net:headlessmc-net-parallel')
    runtimeOnly project(':headlessmc-net:headlessmc-net-java')

    implementation project(':headlessmc-console:headlessmc-progressbar')
    implementation project(':headlessmc-console:headlessmc-progressbar:headlessmc-progressbar-jline')
    implementation project(':headlessmc-util:headlessmc-util-json')
    runtimeOnly project(':headlessmc-util:headlessmc-util-json-jackson')
    implementation project(':headlessmc-config')
    implementation project(':headlessmc-files')
}

dependencies {
    testImplementation testFixtures(project(':headlessmc-net'))
}
