dependencies {
    api project(':headlessmc-platform')

    implementation project(':headlessmc-platform:headlessmc-platform-vanilla')

    api project(':headlessmc-java:headlessmc-java-all')
    api project(':headlessmc-version:headlessmc-version-arg')
    api project(':headlessmc-launcher:headlessmc-launcher-process')

    implementation project(':headlessmc-version')
    implementation project(':headlessmc-version:headlessmc-version-util')
    implementation project(':headlessmc-version:headlessmc-version-service')

    implementation rootProject
    implementation project(':headlessmc-os')
    implementation project(':headlessmc-test')
    implementation project(':headlessmc-util:headlessmc-util-maven')

    api project(':headlessmc-launcher:headlessmc-launcher-profile')
    implementation project(':headlessmc-launcher:headlessmc-launcher-args')
    implementation project(':headlessmc-launcher:headlessmc-launcher-libraries')
    implementation project(':headlessmc-launcher:headlessmc-launcher-logging')
    implementation project(':headlessmc-launcher:headlessmc-launcher-assets')

    implementation project(':headlessmc-auth')
    implementation project(':headlessmc-auth:headlessmc-auth-cdi')

    implementation project(':headlessmc-console:headlessmc-console-cdi')
}
