dependencies {
    implementation project(':headlessmc-version')
    implementation project(':headlessmc-version:headlessmc-version-util')

    implementation project(':headlessmc-net')
    runtimeOnly project(':headlessmc-net:headlessmc-net-java')
    implementation project(':headlessmc-files')
}

dependencies {
    testImplementation testFixtures(project(':headlessmc-files'))
    testImplementation testFixtures(project(':headlessmc-net'))
    testImplementation testFixtures(project(':headlessmc-version'))
}
