package io.github.headlesshq.headlessmc.platform.fabric;

import io.github.headlesshq.headlessmc.util.json.JsonService;
import io.quarkus.runtime.annotations.RegisterResources;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.util.TypeLiteral;
import jakarta.inject.Inject;

import java.io.IOException;
import java.io.InputStream;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;

/**
 * Handles {@link InstallerArtifact}.
 * See {@code build.gradle} for how they are created.
 * The resource can also be found under {@code build/fabric-artifacts.json}.
 */
@ApplicationScoped
@RegisterResources(globs = {InstallerArtifactService.RESOURCE_NAME})
class InstallerArtifactService {
    static final String RESOURCE_NAME = "fabric/fabric-artifacts.json";
    static final String LEGACY_FABRIC = "net.legacyfabric:fabric-installer";
    static final String FABRIC_MC = "net.fabricmc:fabric-installer";

    private final Map<String, InstallerArtifact> artifacts;

    @Inject
    InstallerArtifactService(JsonService jsonService) {
        this.artifacts = loadArtifacts(jsonService);
    }

    public InstallerArtifact getInstaller() {
        return getInstaller(FABRIC_MC);
    }

    public InstallerArtifact getLegacyInstaller() {
        return getInstaller(LEGACY_FABRIC);
    }

    public InstallerArtifact getInstaller(String id) {
        return artifacts.get(id);
    }

    public Collection<InstallerArtifact> all() {
        return artifacts.values();
    }

    private static Map<String, InstallerArtifact> loadArtifacts(JsonService jsonService) {
        // generated by build.gradle
        try (InputStream stream = InstallerArtifactService.class.getClassLoader().getResourceAsStream(RESOURCE_NAME)) {
            Objects.requireNonNull(stream, "fabric-installer resource not found");
            return jsonService.parseRegisteredForReflection(stream, new TypeLiteral<Map<String, InstallerArtifact>>() {});
        } catch (IOException e) {
            throw new IllegalStateException("Failed to get fabric-installer resource", e);
        }
    }

}
